version: '3.9'
services:
  code-analyzer-service:
    container_name: code-analyzer-service
    restart: always
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - code-analyzer-network
    volumes:
      - ./app:/app
    working_dir: /app

  code-analyzer-db:
    container_name: code-analyzer-db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code-analyzer
    ports:
      - "5432:5432"
    networks:
      - code-analyzer-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  code-analyzer-network:
    driver: bridge

volumes:
  postgres_data:
